INSERT INTO CATEGORY (AVAILABLE_CONTENT, PRICE,ID, NAME) VALUES ('10', '4.0',1,'Dutch Films');
INSERT INTO CATEGORY (AVAILABLE_CONTENT, PRICE,ID, NAME) VALUES ('20', '6.0',2,'Dutch Series');
INSERT INTO CATEGORY (AVAILABLE_CONTENT, PRICE,ID, NAME) VALUES ('5', '8.0',3,'International Films');




